name = "roitelet"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[[r2_buckets]]
binding = "ROITELET_BUCKET"
bucket_name = "roitelet-patches"

[[kv_namespaces]]
binding = "ROITELET_META"
id = "a45b1f7fd2254032a03ee439a9768c83"