import 'dart:io';
import 'package:yaml/yaml.dart';

class RoiteletConfigFile {
  final String appId;
  final String workerUrl;
  final String releaseVersion;
  final String pubkeyBase64;

  RoiteletConfigFile({
    required this.appId,
    required this.workerUrl,
    required this.releaseVersion,
    required this.pubkeyBase64,
  });

  Map<String, dynamic> toMap() => {
        'app_id': appId,
        'worker_url': workerUrl,
        'release_version': releaseVersion,
        'pubkey': pubkeyBase64,
      };

  String toYaml() {
    final m = toMap();
    final sb = StringBuffer()
      ..writeln('# roitelet.yaml — generated by `roitelet init`');
    for (final k in m.keys) {
      sb.writeln('$k: "${m[k]}"');
    }
    return sb.toString();
  }

  factory RoiteletConfigFile.fromFile(File f) {
    final doc = loadYaml(f.readAsStringSync()) as YamlMap;
    return RoiteletConfigFile(
      appId: doc['app_id'] as String,
      workerUrl: doc['worker_url'] as String,
      releaseVersion: doc['release_version'] as String,
      pubkeyBase64: doc['pubkey'] as String,
    );
  }
}